# Generated by Django 4.1.1 on 2022-09-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family_name',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Name of Family Name'),
        ),
    ]
