# Generated by Django 4.1.1 on 2022-10-01 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outlay',
            old_name='Outlay_type',
            new_name='outlay_type',
        ),
        migrations.AlterField(
            model_name='outlay',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 1, 18, 6, 52, 45134, tzinfo=datetime.timezone.utc)),
        ),
    ]
