# Generated by Django 4.1.1 on 2022-10-08 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_alter_outlay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlay',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 8, 22, 49, 33, 986165, tzinfo=datetime.timezone.utc)),
        ),
    ]
