# Generated by Django 4.1.1 on 2022-10-10 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_alter_outlay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlay',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 10, 18, 15, 45, 723416, tzinfo=datetime.timezone.utc)),
        ),
    ]
